### ISSUE TITLE
hx_i  :  x coordinate of the heading direction of the ego vehicle

### ISSUE THREAD

**Issue by PierreCKL** [Yiru-Jiao/Two-Dimensional-Time-To-Collision#1]
Hello, i am not sure that i understand what is this vector (or is it a point in the 2d space) : hx_i  :  x coordinate of the heading direction of the ego vehicle, isn't the direction i am heading toward the same as my current velocity vector? 

Thanks for taking time to answer my questions =)

**Comment by Yiru-Jiao** [comment]
Hello PierreCKL,
This is majorly for computing the net distance between vehicles. `hx_i` indeed is the x coordinate of the vector of vehicle i's heading direction, which in most of the cases is aligned with its velocity direction. But when the speed is zero, `vx_i` and `vy_i` will both be zero, and we need to know the heading to compute the closest distance between i and j. For computing time to collision there is no problem to ignoring the cases with zero speed. But I aimed to ensure that every case is covered and we can always use the function CurrentD to compute the net distance for detecting collisions.
